name: PubMed Scraper Workflow

on:
  schedule:
    - cron: '0 18 * * *'  # Exécute le script tous les jours à 18h UTC
  workflow_dispatch:  # Permet un déclenchement manuel du workflow

jobs:
  scrape_pubmed:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Version stable de Python

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter le script PubMed Scraper
        run: python pubmed_scraper.py
