name: PubMed Scraper Workflow

on:
  schedule:
    - cron: '0 18 * * *'  # Exécution tous les jours à 18h UTC
  workflow_dispatch:  # Permet d'exécuter le workflow manuellement
  push:
    branches:
      - main  # Se déclenche aussi quand il y a des changements dans la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run PubMed Scraper
        run: |
          python pubmed_scraper.py

      - name: List files generated
        run: |
          echo "Fichiers générés dans le dossier 'archives' :"
          ls -l archives/

      - name: Commit and push CSV files
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add archives/
          git commit -m "Ajout du fichier CSV du jour" || echo "Rien à commit"
          git push origin main || echo "Aucun changement à pousser"
