jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set git identity (add this step to avoid the identity error)
      - name: Set git identity
        run: |
          git config --global user.email "lena.somano2@gmail.com"
          git config --global user.name "lenatarax"

      # Run the script to scrape data from PubMed
      - name: Run PubMed scraper
        run: python pubmed_scraper.py

      # Archive CSV files (if needed)
      - name: Archive CSV files
        run: |
          git add archives/
          git commit -m "Add new CSV file"
          git push origin main
