name: Run PubMed Scraper Daily

on:
  schedule:
    - cron: '0 18 * * *'  # Exécution tous les jours à 18h UTC
  workflow_dispatch:  # Permet d'exécuter manuellement également

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run PubMed Scraper
        run: |
          python pubmed_scraper.py
          
      - name: Commit and push CSV
        run: |
          git add archives/
          git commit -m "Update CSV with new PubMed results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token secret GitHub pour pousser les changements
